# Generated by Django 5.0.6 on 2024-07-20 00:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_meal_seatcategory_stops_transport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRAIN_ONLY', 'Train Only'), ('BUS_AND_TRAIN', 'Bus and Train')], max_length=20, verbose_name='type')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Recorrido',
                'verbose_name_plural': 'Recorridos',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('dni_or_passport', models.CharField(max_length=50, verbose_name='dni_or_passport')),
                ('origin_country', models.CharField(max_length=100, verbose_name='origin_country')),
                ('emergency_telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='emergency_telephone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date_of_birth')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('w', 'Female')], default='m', help_text='Genero del pasajero', max_length=1, verbose_name='gender')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['dni_or_passport'],
            },
        ),
        migrations.RemoveField(
            model_name='bus',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='seatcategory',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='train',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='enabled',
        ),
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='meal',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='stops',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='train',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='transport',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='JourneySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='departure_time')),
                ('arrival_time', models.DateTimeField(verbose_name='arrival_time')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.journey', verbose_name='journey')),
            ],
            options={
                'verbose_name': 'Cronograma de Recorrido',
                'verbose_name_plural': 'Cronogramas de Recorrido',
                'ordering': ['journey'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('duration', models.DurationField(verbose_name='duration')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
                ('arrival_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_stages', to='dashboard.stops', verbose_name='arrival_stop')),
                ('departure_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_stages', to='dashboard.stops', verbose_name='departure_stop')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dashboard.journey', verbose_name='journey')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transport', verbose_name='transport')),
            ],
            options={
                'verbose_name': 'Etapa de Recorrido',
                'verbose_name_plural': 'Etapas de Recorrido',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='purchase_date')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.passenger', verbose_name='passenger')),
            ],
            options={
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Ventas',
                'ordering': ['purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='DetailsProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit_price')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.purchasereceipt', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'Detalle de la Orden de mercadería',
                'verbose_name_plural': 'Detalles de la Orden de mercadería',
                'ordering': ['receipt'],
            },
        ),
        migrations.CreateModel(
            name='DetailFoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit_price')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.meal', verbose_name='meal')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='dashboard.purchasereceipt', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'Detalle de la Orden de platos',
                'verbose_name_plural': 'Detalles de la Orden de platos',
                'ordering': ['receipt'],
            },
        ),
        migrations.CreateModel(
            name='TicketSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='purchase_date')),
                ('status', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Venta de Boletos',
                'verbose_name_plural': 'Ventas de Boletos',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.passenger', verbose_name='passenger')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.journeyschedule', verbose_name='schedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seat', verbose_name='seat')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='dashboard.ticketsales', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, verbose_name='payment_id')),
                ('payment_type', models.CharField(max_length=50, verbose_name='payment_type')),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='payment_status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ticketsales', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['created_at'],
            },
        ),
    ]
