# Generated by Django 5.0.6 on 2024-07-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_journey_passenger_remove_bus_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['name'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='detailfoodorder',
            options={'ordering': ['receipt'], 'verbose_name': 'Detail Food Order', 'verbose_name_plural': 'Detail Food Orders'},
        ),
        migrations.AlterModelOptions(
            name='detailsproductorder',
            options={'ordering': ['receipt'], 'verbose_name': 'Details Product Order', 'verbose_name_plural': 'Details Product Orders'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['type'], 'verbose_name': 'Journey', 'verbose_name_plural': 'Journeys'},
        ),
        migrations.AlterModelOptions(
            name='journeyschedule',
            options={'ordering': ['journey'], 'verbose_name': 'Journey Schedule', 'verbose_name_plural': 'Journey Schedules'},
        ),
        migrations.AlterModelOptions(
            name='journeystage',
            options={'ordering': ['order'], 'verbose_name': 'Journey Stage', 'verbose_name_plural': 'Journey Stages'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['dni_or_passport'], 'verbose_name': 'Passenger', 'verbose_name_plural': 'Passengers'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['created_at'], 'verbose_name': 'Payments', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['purchase_date'], 'verbose_name': 'Purchase Receipt', 'verbose_name_plural': 'Purchase Receipts'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number'], 'verbose_name': 'Seat', 'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='seatcategory',
            options={'ordering': ['type'], 'verbose_name': 'Seat Category', 'verbose_name_plural': 'Seat Categories'},
        ),
        migrations.AlterModelOptions(
            name='stops',
            options={'ordering': ['name'], 'verbose_name': 'Stop', 'verbose_name_plural': 'Stops'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketsales',
            options={'ordering': ['user'], 'verbose_name': 'Ticket Sale', 'verbose_name_plural': 'Ticket Sales'},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['name'], 'verbose_name': 'Train', 'verbose_name_plural': 'Trains'},
        ),
    ]
