# Generated by Django 5.0.6 on 2024-07-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_bus_options_alter_detailfoodorder_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
