# Generated by Django 5.0.6 on 2024-07-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_category_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
