# Generated by Django 5.0.6 on 2024-07-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_mealcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
