# Generated by Django 5.0.6 on 2024-07-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_meal_description_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='sale',
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.payments', verbose_name='payment'),
        ),
    ]
