# Generated by Django 5.0.6 on 2024-07-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_purchasereceipt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='detailfoodorder',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='detailsproductorder',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='journeyschedule',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticketsales',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status'),
        ),
    ]
