# Generated by Django 5.0.6 on 2024-07-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_bus_status_alter_detailfoodorder_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_id',
            new_name='voucher_no',
        ),
    ]
