# Generated by Django 5.0.6 on 2024-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_payment_status_payments_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('account_money', 'Account Money MP'), ('cash', 'Cash')], default='cash', help_text='Payment Type', max_length=50, verbose_name='gender'),
        ),
    ]
