# Generated by Django 5.0.6 on 2024-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_payments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(blank=True, default='success', max_length=50, null=True, verbose_name='payment_status'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('account_money', 'Account Money MP'), ('cash', 'Cash')], default='cash', help_text='Payment Type', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='voucher_no'),
        ),
    ]
