# Generated by Django 5.0.6 on 2024-08-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_seatcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transport', verbose_name='transport'),
        ),
    ]
