# Generated by Django 5.0.6 on 2024-08-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_seatcategory_description_seatcategory_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatcategory',
            name='transport',
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.journey', verbose_name='journey'),
        ),
    ]
