# Generated by Django 5.0.6 on 2024-08-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_seatcategory_transport_seatcategory_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.CharField(blank=True, choices=[('standar', 'Standar'), ('vip', 'VIP'), ('ejecutive', 'Ejecutive')], default='cash', help_text='Seat Type', max_length=50, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='JourneyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(blank=True, choices=[('standar', 'Standar'), ('vip', 'VIP'), ('ejecutive', 'Ejecutive')], default='cash', help_text='Category', max_length=50, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('status', models.CharField(blank=True, choices=[('h', 'Enabled'), ('d', 'disabled')], default='h', max_length=1, verbose_name='status')),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.journey', verbose_name='journey')),
            ],
            options={
                'verbose_name': 'Journey Price',
                'verbose_name_plural': 'Journey Prices',
                'ordering': ['category'],
            },
        ),
        migrations.DeleteModel(
            name='SeatCategory',
        ),
    ]
