# Generated by Django 5.0.6 on 2024-08-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_seat_category_journeyprices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyschedule',
            name='principal_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transport', verbose_name='principal_transport'),
        ),
        migrations.AddField(
            model_name='ticketsales',
            name='assistance',
            field=models.BooleanField(default=False, verbose_name='assistance'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='detailfoodorder',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='detailsproductorder',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='journeyprices',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='journeyschedule',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.CharField(blank=True, choices=[('standar', 'Standar'), ('vip', 'VIP'), ('ejecutive', 'Ejecutive')], default='cash', help_text='Seat Category', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ticketsales',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('d', 'Deshabilitado')], default='h', max_length=1, verbose_name='status'),
        ),
    ]
