# Generated by Django 5.0.6 on 2024-08-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_journeyschedule_principal_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsales',
            name='assistance',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assistance',
            field=models.BooleanField(default=False, verbose_name='assistance'),
        ),
    ]
